Feature/fix mobile nav
shik4rishuffle/stokelyne pull request #4
Opened 2022-06-02 10:14 UTC by im-fdavies

add mobile nav to fix page layout issues

2022-06-02 18:33 UTC, bnjn commented on src/components/Navbar.jsx
> +		console.log(this.state);
remove for production

2022-06-02 19:24 UTC, bnjn requested changes
One bug to fix (see code comments)

2022-06-02 19:24 UTC, bnjn commented on src/styles/navbar-component.module.css
> +    display: flex;
Causes sub links to display on the same line when clicked or hovered over. Removing this line doesn't appear to break anything but fixes the issue.

2022-06-02 19:24 UTC, bnjn commented on src/styles/navbar-component.module.css
> +    display: flex;
Tested without this line and can't make it break. Will remove in next commit.

2022-06-02 19:27 UTC, bnjn approved these changes
Fixed sub item bug. Also sorted the borked contact form display on mobile.

2022-06-02 19:28 UTC, bnjn approved these changes

2022-06-03 10:30 UTC, shik4rishuffle commented on src/components/Navbar.jsx
> +		console.log(this.state);
good spot

2022-06-03 10:30 UTC, shik4rishuffle commented
> Fixed sub item bug. Also sorted the borked contact form display on mobile.

champion

2022-06-03 10:34 UTC, merged